src/servicePlanningPy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.core.urls"))
]

src/apps/core/models.py
from datetime import date, timedelta
from django.db import models
from django.dispatch import receiver

class ServiceTime(models.Model):
    start_date = models.DateField()
    start_time = models.TimeField(unique=True)
    end_time = models.TimeField()

    def __str__(self):
        return str(self.start_time.strftime("%H:%M %p"))

class Team(models.Model):
    name = models.CharField(max_length=155, unique=True)

    def __str__(self):
        return self.name

class ServiceType(models.Model):
    RECUR_OPTIONS = [
        ('a', 'Weekly'),
        ('b', 'Daily'),
        ('c', 'Every Weekday'),
        ('e', 'Every Other Week'),
        ('d', 'Monthly'),
    ]
    name = models.CharField(max_length=155, unique=True)
    recur = models.CharField(max_length=1,
                            choices=RECUR_OPTIONS,
                            null=True, default='a')
    times = models.ManyToManyField(ServiceTime)
    teams = models.ManyToManyField(Team, blank=True)

    def __str__(self):
        return self.name
    
    @property
    def identifier(self):
        return self.name.split()[0] + str(self.id)

    @property
    def get_events(self):
        return self.event_set.all()

class Event(models.Model):
    service_type = models.ForeignKey(ServiceType, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=155, blank=True, null=True)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

    @property
    def is_active(self):
        if self.date:
            now = date.today()
            if self.date >= now:
                return True
            else:
                return False
        return

    @property
    def get_times(self):
        return [time for time in self.service_type.times.all()]
    
    @property
    def model_name(self):
        return self.__class__.__name__
    


class EventOrder(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.event) + ": Order"

    def get_items(self):
        items = self.orderitem_set.all()
        return items

    @property
    def total_length(self):
        items = self.orderitem_set.all()
        total_seconds =  sum([item.length.total_seconds() for item in items])
        return timedelta(seconds=total_seconds)

@receiver(models.signals.post_save, sender=Event)
def create_event_order(sender, instance, created, **kwargs):
    if created:
        EventOrder.objects.create(event=instance)

class OrderItem(models.Model):
    TYPE_OPTIONS = [
        ('a', 'Item'),
        ('b', 'Header'),
    ]
    order = models.ForeignKey(EventOrder, on_delete=models.CASCADE)
    length = models.DurationField(blank=True, null=True)
    title = models.CharField(max_length=120, blank=True, null=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    person = models.CharField(max_length=120, null=True, blank=True)
    item_type = models.CharField(max_length=1,
                            choices=TYPE_OPTIONS,
                            null=True, default='a')

    def __str__(self):
        return self.title
    
    @property
    def model_name(self):
        return self.__class__.__name__

src/templates/components/OrderItemForm.html
<form id="orderItemForm" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-3">
            <label for="minutes" class="control-label">Minutes</label>
            {{form.minutes}}
        </div>
        <span class="input-addon mt-3"><br>:</span>
        <div class="form-group col-3">
            <label for="seconds" class="control-label">Seconds</label>
            {{form.seconds}}
        </div>
        <div class="form-group col">
            <label for="item_type" class="control-label">Type</label>
            {{form.item_type}}
        </div>
    </div>
    <div class="form-group">
        <label for="title" class="control-label">Title</label>
        {{form.title}}
    </div>
    <div class="form-group">
        <label for="person" class="control-label" >Person</label>
        {{form.person}}
    </div>
    <div class="form-group">
        <label for="description" class="control-label" >Description</label>
        {{form.description}}
    </div>
</form>

src/templates/components/calendar.html
{{ calendar|safe }}

<div class="col-12 order-2">
    <h4 class="text-muted">Upcoming</h4>
    <ul class="upcomming-events">
        {% if events %}
            {% for event in events %}
                <li><a href="{% url 'event' id=event.id %}">
                    {{ event.title }}
                </a></li>
            {% endfor %}
        {% else %}
        <li class="text-muted">No upcoming plans or blockout dates</li>
        {% endif %}
    </ul>
</div>

src/templates/components/header.html
<header>
    <nav class="navbar navbar-expand-sm navbar-dark" 
    style="background-color: #6A9639">
        <a href="{% url 'schedule' %}" class="col-xs-4 navbar-brand">
            Services
        </a>
        {% if user.is_authenticated %}
        <ul class=" col-xs-4 navbar-nav mx-auto">
            <li class="nav-item
            {% if request.resolver_match.url_name == 'schedule' %}active{% endif %}
            "><a href="{% url 'schedule' %}" class="nav-link">
                My Schedule
            </a></li>
            <li class="nav-item
            {% if request.resolver_match.url_name == 'plans' %}active{% endif %}
            "><a href="{% url 'plans' %}" class="nav-link">
                Plans
            </a></li>
            <li class="nav-item"><a href="" class="nav-link
                {% if request.resolver_match.url_name == 'songs' %}active{% endif %}
                ">
                Songs
            </a></li>
            <li class="nav-item"><a href="#" class="nav-link
                {% if request.resolver_match.url_name == 'media' %}active{% endif %}
                ">
                Media
            </a></li>
            <li class="nav-item"><a href="#" class="nav-link
                {% if request.resolver_match.url_name == 'people' %}active{% endif %}
                ">
                People
            </a></li>
        </ul>
        
        <div class="col-xs-4">
            <div class="dropdown">

                <button id="profile" type="button" 
                class="btn rounded-circle btn-dark"
                data-toggle="dropdown" 
                aria-haspopup="true" aria-expanded="false"
                >
                        <i class="fas fa-user"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profile">
                    <a href="" class="dropdown-item">{{ user.full_name }}</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'logout' %}" class="dropdown-item">
                        <i class="fas fa-sign-out-alt"></i>    Log Out
                    </a>
                </div>
            </div>
        </div>
        {% endif %}
      </nav>
</header>

src/templates/components/order.html
<table class="table">
    <thead>
        <tr class="d-flex">
            <th class="col-2" >Length</th>
            <th class="col-6">Title</th>
            <th class="col-2">Person</th>
            <th class="col">
                <a type="button" class="btn schedule-btn bg-transparent" 
                data-toggle="modal" data-target="#itemForm">
                    Add
            </a>
            </th>
            <th class="col">
                <a href="{% url 'export_order_csv' id=event.eventorder.id %}" class="btn schedule-btn bg-transparent">Export</a>
            </a>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for item in event.eventorder.orderitem_set.all %}
            <tr class="d-flex {{ item.get_item_type_display }}">
                <td class="col-2">{{item.length}}</td>
                <td class="col-6">
                    {{item.title}}
                    {% if item.description %}
                    <p class="text-muted p-0 m-0 text-left text-wrap">
                        <small>
                            {{item.description|linebreaks}}
                        </small>
                    </p>
                    {% endif %}

                </td>
                <td class="col-2">{{item.person}}</td>
                <td class="col-2">
                    <a href="{% url 'delete' model=item.model_name id=item.id %}"
                    onclick="return confirm('Are you sure?')"
                    class="delete-item">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                    <a href="{% url 'edit_item' item_id=item.id %}"
                    class="edit-item mx-1">
                        <i class="fa-solid fa-edit"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}

        <tr class="d-flex bg-secondary text-light">
            <td class="col ">{{event.eventorder.total_length}}</td>
        </tr>
        
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="itemForm" tabindex="-1" role="dialog" 
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            {% include 'components/OrderItemForm.html' %}

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" form="orderItemForm" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
  </div>

  <script>
      function removeSigns() {
        var input = document.getElementById('my-input');
        input.value = parseInt(input.value.toString().replace('+', '').replace('-', ''))
      }
  </script>

src/templates/components/teams.html
<div class="row">
    {{event.service_type.team_set}}
    {% for team in event.service_type.teams.all %}
        <div class="col-md-4">
            <div class="card p-2 mb-2">
                <div class="card-body">{{team.name}}</div>
                <div class="card-text">
                    <ul>
                        {% for user in team.user_set.all %}
                        <li>{{user}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    {% endfor %}
</div>